services:
  - type: web
    name: weight-management-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://weight-management-backend.onrender.com/api 