name: Keep Server Awake

on:
  schedule:
    # Run every 14 minutes
    - cron: '*/14 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Ping server
        run: |
          echo "🔄 Pinging GoooFit server at $(date)"
          npm run ping
        env:
          SERVER_URL: https://gooofit.onrender.com
          
      - name: Log completion
        run: |
          echo "✅ Ping completed at $(date)"
          echo "⏰ Next ping will be in ~14 minutes" 