name: Simple Server Ping

on:
  schedule:
    # Run every 14 minutes
    - cron: '*/14 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping server with curl
        run: |
          echo "🔄 Pinging GoooFit server at $(date)"
          
          # Random endpoint selection
          endpoints=(
            "/api/user-success?limit=5"
            "/api/user-success/random"
            "/api/user-success/stats"
            "/api/health"
            "/api/status"
            "/"
            "/health"
            "/status"
          )
          
          # Select random endpoint
          endpoint=${endpoints[$RANDOM % ${#endpoints[@]}]}
          
          # Add random parameters
          timestamp=$(date +%s)
          random_vars=("_t" "v" "cache" "r" "p" "s")
          random_var=${random_vars[$RANDOM % ${#random_vars[@]}]}
          random_val=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 6 | head -n 1)
          
          # Construct URL with random parameters
          url="https://gooofit.onrender.com${endpoint}?${random_var}=${random_val}&_t=${timestamp}"
          
          echo "🎯 Endpoint: ${endpoint}"
          echo "🔗 URL: ${url}"
          
          # Random user agents
          user_agents=(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/121.0"
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/121.0"
            "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/121.0"
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/120.0.0.0"
          )
          
          # Select random user agent
          user_agent=${user_agents[$RANDOM % ${#user_agents[@]}]}
          
          echo "👤 User-Agent: ${user_agent:0:50}..."
          
          # Make the request with random delay
          sleep $((RANDOM % 10 + 1))
          
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "User-Agent: ${user_agent}" \
            -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" \
            -H "Accept-Language: en-US,en;q=0.5" \
            -H "Accept-Encoding: gzip, deflate" \
            -H "Connection: keep-alive" \
            -H "Upgrade-Insecure-Requests: 1" \
            --max-time 30 \
            "${url}")
          
          echo "📊 Response: ${response}"
          
          if [ "$response" = "200" ] || [ "$response" = "404" ]; then
            echo "✅ Server is responding (Status: ${response})"
          else
            echo "⚠️  Server might be sleeping (Status: ${response})"
          fi
          
          echo "⏰ Next ping will be in ~14 minutes"
          echo "────────────────────────────────────────────────────────────────────────────────"
        env:
          SERVER_URL: https://gooofit.onrender.com
          
      - name: Log completion
        run: |
          echo "✅ Ping completed at $(date)"
          echo "🎯 Target: https://gooofit.onrender.com"
          echo "⏰ Next scheduled run: $(date -d '+14 minutes' '+%Y-%m-%d %H:%M:%S')" 